"""create asset and telemetry tables

Revision ID: 1681ee07d417
Revises: 
Create Date: 2026-09-24 08:06:51.280097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1681ee07d417'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('criticality', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=True)
    op.create_table('telemetry_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('source_address', sa.String(length=100), nullable=True),
    sa.Column('destination_address', sa.String(length=100), nullable=True),
    sa.Column('protocol', sa.String(length=50), nullable=True),
    sa.Column('command', sa.String(length=100), nullable=True),
    sa.Column('register_address', sa.Integer(), nullable=True),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('process_id', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_events_asset_id'), 'telemetry_events', ['asset_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_event_id'), 'telemetry_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_telemetry_events_process_id'), 'telemetry_events', ['process_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_timestamp'), 'telemetry_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telemetry_events_timestamp'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_process_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_event_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_asset_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
