"""create correlations table

Revision ID: b7d7de667c8d
Revises: edb172d5b577
Create Date: 2026-09-24 11:36:28.961666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7d7de667c8d'
down_revision: Union[str, Sequence[str], None] = 'edb172d5b577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.Column('control_event_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('process_id', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('event_ids_json', sa.JSON(), nullable=False),
    sa.Column('detection_ids_json', sa.JSON(), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlations_asset_id'), 'correlations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_correlations_control_event_id'), 'correlations', ['control_event_id'], unique=True)
    op.create_index(op.f('ix_correlations_correlation_id'), 'correlations', ['correlation_id'], unique=True)
    op.create_index(op.f('ix_correlations_process_id'), 'correlations', ['process_id'], unique=False)
    op.create_index(op.f('ix_correlations_timestamp'), 'correlations', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_correlations_timestamp'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_process_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_correlation_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_control_event_id'), table_name='correlations')
    op.drop_index(op.f('ix_correlations_asset_id'), table_name='correlations')
    op.drop_table('correlations')
    # ### end Alembic commands ###
