"""create detections table

Revision ID: edb172d5b577
Revises: 1681ee07d417
Create Date: 2026-09-24 10:48:27.178026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edb172d5b577'
down_revision: Union[str, Sequence[str], None] = '1681ee07d417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('detection_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('asset_id', sa.String(length=100), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('evidence_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_asset_id'), 'detections', ['asset_id'], unique=False)
    op.create_index(op.f('ix_detections_detection_id'), 'detections', ['detection_id'], unique=True)
    op.create_index(op.f('ix_detections_event_id'), 'detections', ['event_id'], unique=False)
    op.create_index(op.f('ix_detections_rule_id'), 'detections', ['rule_id'], unique=False)
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_index(op.f('ix_detections_rule_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_event_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_detection_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_asset_id'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
